/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellAnalyticsRouteImport } from './routes/_shell/analytics'
import { Route as ShellCalendarRouteImport } from './routes/_shell/calendar'
import { Route as ShellJournalRouteImport } from './routes/_shell/journal'
import { Route as ShellMoreRouteImport } from './routes/_shell/more'
import { Route as ShellRulesRouteImport } from './routes/_shell/rules'
import { Route as ShellSettingsRouteImport } from './routes/_shell/settings'
import { Route as ShellTradesRouteImport } from './routes/_shell/trades'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAnalyticsRoute = ShellAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCalendarRoute = ShellCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => ShellRoute,
} as any)
const ShellJournalRoute = ShellJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMoreRoute = ShellMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRulesRoute = ShellRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTradesRoute = ShellTradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/analytics': typeof ShellAnalyticsRoute
  '/calendar': typeof ShellCalendarRoute
  '/journal': typeof ShellJournalRoute
  '/more': typeof ShellMoreRoute
  '/rules': typeof ShellRulesRoute
  '/settings': typeof ShellSettingsRoute
  '/trades': typeof ShellTradesRoute
}
export interface FileRoutesByTo {
  '/analytics': typeof ShellAnalyticsRoute
  '/calendar': typeof ShellCalendarRoute
  '/journal': typeof ShellJournalRoute
  '/more': typeof ShellMoreRoute
  '/rules': typeof ShellRulesRoute
  '/settings': typeof ShellSettingsRoute
  '/trades': typeof ShellTradesRoute
  '/': typeof ShellIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/analytics': typeof ShellAnalyticsRoute
  '/_shell/calendar': typeof ShellCalendarRoute
  '/_shell/journal': typeof ShellJournalRoute
  '/_shell/more': typeof ShellMoreRoute
  '/_shell/rules': typeof ShellRulesRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/trades': typeof ShellTradesRoute
  '/_shell/': typeof ShellIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/calendar'
    | '/journal'
    | '/more'
    | '/rules'
    | '/settings'
    | '/trades'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/analytics'
    | '/calendar'
    | '/journal'
    | '/more'
    | '/rules'
    | '/settings'
    | '/trades'
    | '/'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/analytics'
    | '/_shell/calendar'
    | '/_shell/journal'
    | '/_shell/more'
    | '/_shell/rules'
    | '/_shell/settings'
    | '/_shell/trades'
    | '/_shell/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/analytics': {
      id: '/_shell/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof ShellAnalyticsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/calendar': {
      id: '/_shell/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof ShellCalendarRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/journal': {
      id: '/_shell/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof ShellJournalRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/more': {
      id: '/_shell/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof ShellMoreRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/rules': {
      id: '/_shell/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof ShellRulesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/trades': {
      id: '/_shell/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof ShellTradesRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAnalyticsRoute: typeof ShellAnalyticsRoute
  ShellCalendarRoute: typeof ShellCalendarRoute
  ShellJournalRoute: typeof ShellJournalRoute
  ShellMoreRoute: typeof ShellMoreRoute
  ShellRulesRoute: typeof ShellRulesRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellTradesRoute: typeof ShellTradesRoute
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAnalyticsRoute: ShellAnalyticsRoute,
  ShellCalendarRoute: ShellCalendarRoute,
  ShellJournalRoute: ShellJournalRoute,
  ShellMoreRoute: ShellMoreRoute,
  ShellRulesRoute: ShellRulesRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellTradesRoute: ShellTradesRoute,
  ShellIndexRoute: ShellIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
